import React from 'react';
import { Lock, Key, Server, Cpu } from 'lucide-react';
import './PublicPages.css';

export const SecurityPage: React.FC = () => {
  return (
    <div className="landing-page">
      <section className="page-hero-section">
        <div className="landing-container">
          <h1 className="hero-title">Security & Cryptographic Architecture</h1>
          <p className="hero-description">
            Zero-Knowledge principles built into every layer. We never store or transmit your master password or unencrypted vault data.
          </p>
        </div>
      </section>

      <section className="features-section">
        <div className="landing-container">
          <div className="security-detail-list">
            <div className="security-detail-card">
              <div className="security-detail-header">
                <Key className="security-detail-icon" />
                <h3>1. Account Authentication vs. Vault Encryption</h3>
              </div>
              <p>
                Logging into your VaultGuard account authenticates your web session via a client-derived authentication key. Account authentication does <strong>not</strong> derive or expose your Master Encryption Key (MEK). Your vault remains locked until you enter your master password to derive the MEK in browser memory.
              </p>
            </div>

            <div className="security-detail-card">
              <div className="security-detail-header">
                <Lock className="security-detail-icon" />
                <h3>2. AES-256-GCM Authenticated Encryption</h3>
              </div>
              <p>
                All vault item fields (titles, usernames, passwords, notes, card details) are serialized into JSON payloads and encrypted using AES-256-GCM with unique 96-bit (12-byte) nonces generated by <code>crypto.getRandomValues()</code>. Nonce reuse is strictly impossible.
              </p>
            </div>

            <div className="security-detail-card">
              <div className="security-detail-header">
                <Cpu className="security-detail-icon" />
                <h3>3. Memory Security Lifecycle</h3>
              </div>
              <p>
                The Master Encryption Key exists solely in application memory (RAM) while unlocked. Closing your browser, refreshing, or locking the vault purges memory references on a best-effort basis. The MEK is never written to <code>localStorage</code>, <code>sessionStorage</code>, <code>IndexedDB</code>, or cookies.
              </p>
            </div>

            <div className="security-detail-card">
              <div className="security-detail-header">
                <Server className="security-detail-icon" />
                <h3>4. Server Data Isolation</h3>
              </div>
              <p>
                The backend receives and stores only ciphertext blobs, salt parameters, and password verifiers. The server has zero knowledge of your vault content or master password.
              </p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};
